const actionTypes = {
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  ADD_HISTORY_ITEM: 'ADD_HISTORY_ITEM',
  UPDATE_EXCHANGE_AMOUNT: 'UPDATE_EXCHANGE_AMOUNT',
  REMOVE_HISTORY_ITEM: 'REMOVE_HISTORY_ITEM'
};

export default actionTypes;
